name: Update Homework Page

on:
  push:
    branches:
      - homework

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          ref: homework
          
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Homework JSON
        run: |
          python - <<EOF

          import json
          import os
          from datetime import datetime

          homework = []
          for filename in os.listdir('.'):
              if filename.endswith('.pdf'):
                  try:
                      parts = filename[:-4].split('__', 2)
                      if len(parts) != 3:
                          raise ValueError("Incorrect number of parts")

                      title = parts[0].replace("_", " ")
                      date_str = parts[1]
                      description = parts[2].replace("_", " ")
                      date = datetime.strptime(date_str, '%Y-%m-%d').strftime('%Y-%m-%d')

                      homework.append({
                          "title": title,
                          "description": description,
                          "date": date,
                          "pdf_link": filename
                      })
                  except ValueError as e:
                      print(f"Skipping {filename}: {e}")
                      continue

          with open('homework.json', 'w') as f:
              json.dump(homework, f, indent=4)

          EOF

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
    
      - name: Create homework directory  
        run: mkdir -p gh-pages/homework

      - name: Move files to homework directory 
        run: |
          cp *.pdf gh-pages/homework/
          cp homework.json gh-pages/homework/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages 
          publish_branch: gh-pages

          